# Generated by Django 4.0.1 on 2022-05-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'verbose_name': 'Catálogo', 'verbose_name_plural': 'Catálogo'},
        ),
        migrations.AddField(
            model_name='catalogo',
            name='caratula',
            field=models.ImageField(null=True, upload_to='catalogo', verbose_name='Carátula'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='link_sptf',
            field=models.URLField(blank=True, null=True, verbose_name='Link Spotify'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='titulo',
            field=models.CharField(default='Nombre de la Obra', max_length=200, verbose_name='Título'),
        ),
    ]
