# Generated by Django 4.0.1 on 2022-05-20 22:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_catalogo_options_catalogo_caratula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBanda', models.CharField(default='Nombre de la Banda', max_length=200, verbose_name='Nombre')),
                ('imgBanda', models.ImageField(null=True, upload_to='bandas', verbose_name='Imagen Banda')),
                ('descripBanda', models.TextField(null=True, verbose_name='Descripción')),
                ('link_sptf', models.URLField(blank=True, null=True, verbose_name='Link Spotify')),
                ('link_bndcmp', models.URLField(blank=True, null=True, verbose_name='Link BandCamp')),
                ('link_ytb', models.URLField(blank=True, null=True, verbose_name='Link YouTube')),
                ('link_ig', models.URLField(blank=True, null=True, verbose_name='Link Instagram')),
                ('link_fb', models.URLField(blank=True, null=True, verbose_name='Link Facebook')),
                ('link_tw', models.URLField(blank=True, null=True, verbose_name='Link Twitter')),
            ],
            options={
                'verbose_name': 'banda',
                'verbose_name_plural': 'bandas',
            },
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nombre de la Obra', max_length=200, verbose_name='Título')),
                ('caratula', models.ImageField(null=True, upload_to='catalogo', verbose_name='Carátula')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('descripDisco', models.TextField(null=True, verbose_name='Descripción')),
                ('link_sptf', models.URLField(blank=True, null=True, verbose_name='Link Spotify')),
                ('link_bndcmp', models.URLField(blank=True, null=True, verbose_name='Link BandCamp')),
                ('link_ytb', models.URLField(blank=True, null=True, verbose_name='Link YouTube')),
                ('link_tienda', models.URLField(blank=True, null=True, verbose_name='Link Tienda Nacional')),
                ('rol', models.CharField(default='Rol en el disco', max_length=200, verbose_name='Rol en el disco')),
                ('descripción', models.TextField(null=True, verbose_name='Descripción de la colaboración')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.banda', verbose_name='Banda')),
            ],
            options={
                'verbose_name': 'disco',
                'verbose_name_plural': 'discos',
            },
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArt', models.CharField(default='Nombre Artístico', max_length=200, verbose_name='Nombre Artístico')),
                ('nombreReal', models.CharField(default='Nombre Real', max_length=200, null=True, verbose_name='Nombre Real')),
                ('imgMusico', models.ImageField(null=True, upload_to='musicos', verbose_name='Imagen Músico')),
                ('link_sptf', models.URLField(blank=True, null=True, verbose_name='Link Spotify')),
                ('link_bndcmp', models.URLField(blank=True, null=True, verbose_name='Link BandCamp')),
                ('link_ytb', models.URLField(blank=True, null=True, verbose_name='Link YouTube')),
                ('link_ig', models.URLField(blank=True, null=True, verbose_name='Link Instagram')),
                ('link_fb', models.URLField(blank=True, null=True, verbose_name='Link Facebook')),
                ('link_tw', models.URLField(blank=True, null=True, verbose_name='Link Twitter')),
                ('rol', models.CharField(default='Rol en la banda', max_length=200, verbose_name='Rol en la banda')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo actualmente')),
                ('bandas', models.ManyToManyField(related_name='get_posts', to='catalogo.Banda', verbose_name='banda')),
            ],
            options={
                'verbose_name': 'Músico',
                'verbose_name_plural': 'Músicos',
            },
        ),
        migrations.DeleteModel(
            name='Catalogo',
        ),
        migrations.AddField(
            model_name='disco',
            name='musicos',
            field=models.ManyToManyField(related_name='get_posts', to='catalogo.Musico', verbose_name='Músicos'),
        ),
    ]
