# Generated by Django 4.0.1 on 2022-05-23 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_banda_disco_musico_delete_catalogo_disco_musicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='descripción',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='rol',
        ),
        migrations.AlterField(
            model_name='banda',
            name='nombreBanda',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='musico',
            name='bandas',
            field=models.ManyToManyField(related_name='get_posts', to='catalogo.Banda', verbose_name='bandas'),
        ),
        migrations.AlterField(
            model_name='musico',
            name='nombreArt',
            field=models.CharField(max_length=200, verbose_name='Nombre Artístico'),
        ),
        migrations.AlterField(
            model_name='musico',
            name='nombreReal',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre Real'),
        ),
        migrations.CreateModel(
            name='ProduccionDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'Producción Musical'), (2, 'Edición y Mezcla'), (3, 'Masterización'), (4, 'Músico invitado'), (5, 'Otro')], verbose_name='Rol en la Producción')),
                ('descripción', models.TextField(null=True, verbose_name='Descripción de la colaboración')),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.disco', verbose_name='Disco')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.musico', verbose_name='Músico')),
            ],
            options={
                'order_with_respect_to': 'disco',
                'unique_together': {('disco', 'musico')},
            },
        ),
        migrations.CreateModel(
            name='IntegranteBanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'Voz'), (2, 'Bateria'), (3, 'Bajo'), (4, 'Guitarra'), (5, 'Teclado/Piano'), (6, 'Vientos'), (7, 'Cuerdas'), (5, 'Otro')], verbose_name='Rol en la Producción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo actualmente')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.banda', verbose_name='Banda')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.musico', verbose_name='Músico')),
            ],
            options={
                'order_with_respect_to': 'banda',
                'unique_together': {('banda', 'musico')},
            },
        ),
    ]
