# Generated by Django 4.0.1 on 2022-05-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_disco_descripción_remove_disco_rol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producciondisco',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='musicos',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='bandas',
        ),
    ]
