# Generated by Django 4.0.1 on 2022-05-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_rename_descripción_producciondisco_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantebanda',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Voz'), (2, 'Bateria'), (3, 'Bajo'), (4, 'Guitarra'), (5, 'Teclado/Piano'), (6, 'Vientos'), (7, 'Cuerdas'), (5, 'Otro')], verbose_name='Rol en la Banda'),
        ),
    ]
