# Generated by Django 4.0.1 on 2022-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_integrantebanda_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='link_tienda',
        ),
        migrations.AddField(
            model_name='disco',
            name='link_tienda_cas',
            field=models.URLField(blank=True, null=True, verbose_name='Link Tienda Nacional CASSETTE'),
        ),
        migrations.AddField(
            model_name='disco',
            name='link_tienda_cd',
            field=models.URLField(blank=True, null=True, verbose_name='Link Tienda Nacional CD'),
        ),
        migrations.AddField(
            model_name='disco',
            name='link_tienda_vin',
            field=models.URLField(blank=True, null=True, verbose_name='Link Tienda Nacional VINILO'),
        ),
    ]
