# Generated by Django 4.0.1 on 2022-06-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_disco_link_sptf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='link_sptf',
            field=models.TextField(max_length=300, null=True, verbose_name='Código inserción desde Spotify'),
        ),
    ]
