# Generated by Django 4.0.1 on 2022-07-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_disco_link_sptf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='link_bndcmp',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='link_bndcmp',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='link_bndcmp',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='link_sptf',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='link_ytb',
        ),
        migrations.AddField(
            model_name='banda',
            name='link_apple',
            field=models.URLField(blank=True, null=True, verbose_name='Link Apple Music'),
        ),
        migrations.AddField(
            model_name='banda',
            name='link_dzr',
            field=models.URLField(blank=True, null=True, verbose_name='Link Deezer'),
        ),
        migrations.AddField(
            model_name='banda',
            name='link_tdl',
            field=models.URLField(blank=True, null=True, verbose_name='Link Tidal'),
        ),
        migrations.AddField(
            model_name='disco',
            name='link_apple',
            field=models.URLField(blank=True, null=True, verbose_name='Link Apple Music'),
        ),
        migrations.AddField(
            model_name='disco',
            name='link_dzr',
            field=models.URLField(blank=True, null=True, verbose_name='Link Deezer'),
        ),
        migrations.AddField(
            model_name='disco',
            name='link_tdl',
            field=models.URLField(blank=True, null=True, verbose_name='Link Tidal'),
        ),
    ]
