# Generated by Django 4.0.1 on 2022-07-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_remove_banda_link_bndcmp_remove_disco_link_bndcmp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='link_dzr',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='link_tdl',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='link_dzr',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='link_tdl',
        ),
    ]
