# Generated by Django 4.0.1 on 2022-07-01 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_remove_banda_link_dzr_remove_banda_link_tdl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
    ]
