# Generated by Django 4.0.1 on 2022-07-01 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_disco_fecha2_alter_disco_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
