# Generated by Django 4.0.1 on 2022-07-01 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_alter_disco_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='fecha2',
        ),
        migrations.AlterField(
            model_name='disco',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
    ]
