# Generated by Django 4.0.1 on 2022-07-01 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_remove_disco_fecha2_alter_disco_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='fecha2',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
