# Generated by Django 4.0.1 on 2022-07-01 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_disco_fecha2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='fecha2',
        ),
        migrations.AddField(
            model_name='disco',
            name='fechaDisco',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
