# Generated by Django 4.0.1 on 2022-07-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_remove_disco_fecha2_disco_fechadisco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='fecha',
        ),
        migrations.AddField(
            model_name='disco',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
