# Generated by Django 4.0.1 on 2022-07-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_remove_disco_fecha_disco_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='order',
        ),
    ]
